### PR TITLE
Get GPS info

### PR DESCRIPTION
**Pull request by lesire**
Deserialize the GPS part of navdata messages when the Parrot Flight Recorder is plugged to the drone
If property 'enable_navdata_gps' is True, the GPS data is published in the /ardrone/navdata_gps topic

### CODE REVIEW

**Comment by mani-monaj** [comment]
Hi @lesire, can you please test the `hydro-devel` branch and apply your changes on top of that?

**Comment by mani-monaj** [comment]
A GPS module is on its way, so I will be able to test your changes. Any updates on merging your changes into `hydro-devel`?

**Comment by lesire** [comment]
Hi Mani,

Sorry, but I am currently out of my office, and I won't be able to test 
the hydro-devel branch till around 10 days.

Regards,

Charles

Le 16.03.2014 01:40, Mani Monajjemi a écrit :

**Comment by lesire** [comment]
Hello,

The GPS patches also work well on the hydro-devel branch.

Do you want to accept the pull request on 'catkin' and then merge with 'hydro-devel', or do you need that I remake the pull request directly on the hydro-devel branch?

**Comment by mani-monaj** [comment]
Thank you for the hard work @lesire . I will apply the patch manually.

**Comment by lesire** [comment]
Hi.
What's the status of this request? Do you plan to apply it to hydro-devel?

**Comment by mani-monaj** [comment]
Yes, I am working on it.

**Comment by mani-monaj** [comment]
Thanks @lesire again. I applied your changes to a temporary _gps_ branch with minor modifications.  (on top of _hydro-devel_). I will test it more. I will also add ROS standard GPS publisher to the driver.

**Comment by lesire** [comment]
Good! Publishing standard GPS messages is on my TODO list, but I won't have time to work on time in the coming days...

**Comment by wiseman** [comment]
@lesire I'm curious, where did you find the definitions of the GPS data structure?

**Comment by lesire** [comment]
I know some developpers at Parrot ;)

**Comment by mani-monaj** [comment]
Thank you. Closing in favour of AutonomyLab/ardronelib@ebf2e656d91dca4c0b84f233f29e3b283619f35e

**Pull request closed without merging**
