### PR TITLE
add a magnetometer topic

### PR DESCRIPTION
**Pull request by sameerparekh**
Hi Mani-- I added some code to publish out the magnetometer data on its own topic. I also reformatted a few bits to make it a little easier to read.

### CODE REVIEW

**Comment by mani-monaj** [comment]
Thank you very much @sameerparekh . I added your proposed changes to the [dev-unstable branch](https://github.com/AutonomyLab/ardrone_autonomy/tree/dev-unstable). Because of #26 I need to test the new features more before merging them into master. Could you please put some time and test the changes in the `dev-unstable` branch?

**Comment by sameerparekh** [comment]
I've done a quick test of dev-unstable and it appears to work fine.  

-s

**Comment by mani-monaj** [comment]
Thank you very much for your feedback.

**Comment by mani-monaj** [comment]
FIxed in 0dc6a2a84bb2bd25f5cccb88bf35a14cd6e88860

**Pull request closed without merging**
