### PR TITLE
Minimal changes to make multiple ardrone_autonomy instances run on the s...

### PR DESCRIPTION
**Pull request by kbogert**
...ame computer

I've tested this with two drones (1.0 and 2.0) and can receive the video and navdata streams simultaneously without issue.

### CODE REVIEW

**Comment by mani-monaj** [comment]
Thank you. I believe this can be closed in favour of AutonomyLab/ardronelib#2

**Comment by kbogert** [comment]
I was leaving this open as a reminder that the current binary and source still build ardrone_autonomy without this support.  Could you please do a release soon? Preferably for hydro if possible as we're still stuck with that release.

**Comment by mani-monaj** [comment]
Fair enough. I am working on a new release and it will be released for Hydro as well.

**Comment by michalMalujdy** [comment]
Hello, is there anyone that could explain step-by-step solution how to spawn and control multiple AR.Drones in Gazebo simulator? I would much appreciate it.

**Pull request closed without merging**
