### PR TITLE
Enable Zero-Command without Hovering

### PR DESCRIPTION
**Pull request by JakobEngel**
Very simple change; the drone only is set to hover mode if all six Twist parameters are zero.

=> by sending ((0,0,0),(0,0,0)) it is still set to hovering, by setting angular.x or angular.y (which currently is completely unused) to e.g. 1, it is sent a zero-command without hovering.

### CODE REVIEW

**Comment by mikehamer** [comment]
Hey @JakobEngel, we've implemented a fix for this in #31 and are discussing it there

**Comment by JakobEngel** [comment]
yes, well, as I understand it you just add a parameter, i.e. you have to decide on startup whether to hover on 0-commands or not.

I'd like to switch hovering on/off in real-time, and I don't see why the two unused parameters in Twist shouldnt be used for that; in particular because it's more consistent with the SDK commands sent (hover yes/no is sent with every command to the drone anyway), and only requires two additional lines in the code.

**Comment by mikehamer** [comment]
Good point. Perhaps on-the-fly hover enable/disable as you've suggested is the way to go.

On a related topic, what is your opinion on reconfiguring the drone post-launch/in-flight? We have a few suggestions for the architecture in #31 which also affect the hover enable/disable – I'd be interested in your feedback. Cheers!

**Comment by mani-monaj** [comment]
@mikehamer I think it is better to remove the two new parameters `command_disable_hover` and `command_always_send` and implement this feature as @JakobEngel proposed.

**Comment by mikehamer** [comment]
Done, see the above pull request! :-)

**Comment by mani-monaj** [comment]
Fixed in #38.

**Pull request closed without merging**
