### PR TITLE
Add workaround for bad GENERIC_TARGET_LIBRARY

### PR DESCRIPTION
**Pull request by cottsay**
Originally https://github.com/AutonomyLab/ardrone_autonomy/pull/92

### CODE REVIEW

**Comment by cottsay** [comment]
Hold on, there is an application error.

**Comment by cottsay** [comment]
Okay, fixed now.

**Comment by mani-monaj** [comment]
Thank you very much. I will do a quick regression test very soon and merge your changes in.

**Comment by mani-monaj** [comment]
@cottsay The `ARDroneLib` is now being built using an [external repository](https://github.com/AutonomyLab/ardronelib) which includes our custom patches. Could you please check the newest `hydro-devel`, apply your patch to the new repo and then create a new pull request (on other repo)?

**Comment by cottsay** [comment]
Closed in favor of https://github.com/AutonomyLab/ardronelib/pull/1

**Pull request closed without merging**
